spring:
  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/movies?useSSL=false
    username: root
    tomcat:
      max-active: 4
      max-idle: 4
      min-idle: 4
      initial-size: 4

  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp

logging.level:
  root: WARN
  org.superbiz.moviefun: DEBUG

s3:
  accessKey: AKIAJQTUFHPLLNDIBCWQ
  secretKey: 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
  bucketName: student-artifacts-bangalore-10

albums:
  url: http://localhost:8081/albums
movies:
  url: http://localhost:8082/movies